WITH JULY_TOTAL AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN JULY_TOTAL JT ON FH.FLAVOR = JT.FLAVOR
ORDER BY (FH.TOTAL_ORDER + JT.TOTAL_ORDER) DESC
LIMIT 3