SELECT YEAR(os.SALES_DATE) as YEAR, MONTH(os.SALES_DATE) as MONTH, ui.GENDER, COUNT(DISTINCT os.user_id ) as USERS
FROM ONLINE_SALE os
LEFT JOIN USER_INFO ui ON os.USER_ID = ui.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
