SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID in (select car_id from CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    where DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' and '2022-10'
                group by car_id
                having count(*) >= 5)
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING RECORDS >= 1
ORDER BY MONTH, CAR_ID DESC;
